name: Lint

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter:
          - 'mypy'
          - 'ruff check'
          - 'isort --check'
          - 'black --check'
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        run: |
          python -m pip install pipx
          pipx install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: ${{ linter }} src test
